# Use the official Golang image
FROM golang:1.25

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Copy the rest of the application source code
COPY . .

# Command to run the application using air
CMD ["air", "-c", "air.toml"]
